apiVersion: v1
kind: Service
metadata:
  name: speed-demo-service
spec:
  type: NodePort
  selector:
    app: speed-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
      nodePort: 30090