apiVersion: v1
kind: Deployment
metadata:
  name: speed-demo-deployment
  labels:
    app: speed-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speed-demo
  template:
    metadata:
      labels:
        app: speed-demo
    spec:
      containers:
      - name: speed-demo
        image: flexrentalsolutions/speed-demo:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: speed-demo-service
spec:
  type: NodePort
  selector:
    app: speed-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
      nodePort: 30090
