apiVersion: apps/v1
kind: Deployment
metadata:
  name: speed-demo-deployment
  labels:
    app: speed-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speed-demo
  template:
    metadata:
      labels:
        app: speed-demo
    spec:
      containers:
      - name: speed-demo
        image: flexrentalsolutions/speed-demo:latest
        ports:
        - containerPort: 8090